### model
latent_action_model_config: 
  _target_: uni_world_model.latent_action_model.models.latent_action_continue_tokenizer.LatentActionModel
  ## image channel
  in_dim: 3
  model_dim: 1024
  latent_dim: 32
  patch_size: 14
  enc_blocks: 16
  dec_blocks: 16
  num_heads: 16
  training: True
  loss_config:
    use_abs_recons_loss: False
    kl_loss_w: 1.0
    recon_loss_w: 1.0
    perceptual_loss_w: 1.0

### dataset
dataset_config:
  data_type: "video_npz"
  # npz_dir: "/mnt/workspace/caizhejia.czj/task_ABC_D" 
  npz_dir: "/mnt/workspace/caizhejia.czj/task_ABC_D" 
  rgb_shape: [200, 200]
  skip_frame: 9

dataloader_config:
  bs_per_gpu: 32
  workers_per_gpu: 7
  prefetch_factor: 2

rgb_preprocessor_config: 
  model_vision_type: "raw"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true

### training
training_config:
  num_epochs: 100
  num_warmup_epochs: 1
  print_steps: 100
  lr_max: 0.0001
  weight_decay: 0.0001
  gradient_accumulation_steps: 1
  save_epochs: 1
  save_steps: 1000
  save_path: "/mnt/workspace/caizhejia.czj/continuous_rgb_skipframe6_0821"
  resume_ckpt_path: null