### model
latent_action_model_config: 
  _target_: uni_world_model.latent_action_model.models.latent_action_dino_continue_tokenizer.LatentActionDINOContinueTokenizer
  dino_model: 
    _target_: uni_world_model.latent_action_model.modules.dinov2_encoder.DinoV2Encoder
    pretrained_model_name_or_path: "/mnt/workspace/czj/models/dinov2-giant"
  dino_dim: 1536
  model_dim: 768
  latent_dim: 128
  patch_size: 14
  enc_blocks: 12
  dec_blocks: 12
  num_heads: 12
  freeze_vision: True
  loss_config:
    use_abs_recons_loss: False
    kl_loss_w: 0.01
    recon_loss_w: 1.0

### dataset
dataset_config:
  data_type: "video_npz"
  npz_dir: "/mnt/workspace/caizhejia.czj/task_ABC_D" 
  # npz_dir: "/mnt/workspace/caizhejia.czj/task_ABC_D" 
  rgb_shape: [200, 200]
  skip_frame: 5

dataloader_config:
  bs_per_gpu: 32
  workers_per_gpu: 7
  prefetch_factor: 2

rgb_preprocessor_config: 
  model_vision_type: "raw"
  vision_aug_config: 
    do_random_resized_crop: false
    do_random_shift: true

### training
training_config:
  num_epochs: 100
  num_warmup_epochs: 1
  print_steps: 10
  lr_max: 0.0001
  weight_decay: 0.0001
  gradient_accumulation_steps: 2
  save_epochs: 1
  save_steps: 1000
  save_path: "/mnt/workspace/czj/worldmodel-bf16/UniWorldModel-256x4-skipframe5/logs/latent_action_dino_continue_tokenizer_trained_on_calvin/"
  resume_ckpt_path: null